### ISSUE TITLE
n8n-nodes-formbricks missing in NPM registry

### ISSUE THREAD

**Issue by bigbeka** [formbricks/n8n-node#3]
Does anyone know why http://registry.npmjs.org/n8n-nodes-formbricks is empty?

I am trying to install community n8n-node-formbricks on my n8n instance, both n8n UI and n8n CLI install's are showing error (I have also tried ping @1.0.2 but no luck):

```
~ $ npm i n8n-node-formbricks
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/n8n-node-formbricks - Not found
npm ERR! 404 
npm ERR! 404  'n8n-node-formbricks@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /home/node/.npm/_logs/2024-06-25T13_27_20_505Z-debug-0.log
```

**Comment by mattinannt** [comment]
Hi :-) I assigned this issue to the team and we will also try to reproduce the issue and then find a solution :-)

**Comment by Dhruwang** [comment]
Hey @bigbeka , seems like package name is incorrect here 🤔
Can you please try `npm i @formbricks/n8n-nodes-formbricks` 😊

https://www.npmjs.com/package/@formbricks/n8n-nodes-formbricks

**Comment by bigbeka** [comment]
Hi @Dhruwang Thanks for your reply. Your suggestion works both in CLI and GUI.
For some reason, other community plugins for n8n install without `@reponame` and they have contents in their registry URL: `https://registry.npmjs.org/n8n-node-formbricks` vs `https://www.npmjs.com/package/@webanimus/n8n-nodes-fider`
